# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT

meta:
  site: example
  comment: example tag list
tags:
  - name: VALVE_OPEN
    namespace: TAGS
    description: bool valve
    type: bool
    default_value: 1

  - name: VALVE_CLOSED
    namespace: TAGS
    description: bool valve
    type: bool
    default_value: 0

  - name: FLOW_A
    namespace: TAGS
    description: int16 flow
    type: int16
    default_value: -325

  - name: FLOW_B
    namespace: TAGS
    description: uint16 flow
    type: uint16
    default_value: 325

  - name: PRESSURE_A
    namespace: TAGS
    description: int32 flow
    type: int32
    default_value: 325

  - name: PRESSURE_B
    namespace: TAGS
    description: uint32 flow
    type: uint32
    default_value: 325

  - name: FLEX_A
    namespace: TAGS_B
    description: float32 flex
    type: float32
    default_value: 3252.2

  - name: FLEX_B
    namespace: TAGS_B
    description: float64 flex
    type: float64
    default_value: -267
