# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT

meta:
  site: example
  comment: example tag list
tags:
  - name: TEST_BOOL
    namespace: TEST
    description: test boolean
    type: bool
    default_value: 1

  - name: TEST_INT16
    namespace: TEST
    description: test int16
    type: int16
    default_value: -100

  - name: TEST_UINT16
    namespace: TEST
    description: test uint16
    type: uint16
    default_value: 100

  - name: TEST_INT32
    namespace: TEST
    description: test int32
    type: int32
    default_value: -100

  - name: TEST_UINT32
    namespace: TEST
    description: test uint32
    type: uint32
    default_value: 100

  - name: TEST_FLOAT64
    namespace: TEST
    description: test float64
    type: float64
    default_value: 3.1459

  - name: TEST_FLOAT32
    namespace: TEST
    description: test float32
    type: float32
    default_value: 3.1459
