// SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
//
// SPDX-License-Identifier: MIT

package open62541

type UA_TYPE int

const (
	UA_TYPES_BOOLEAN         UA_TYPE = 0
	UA_TYPES_SBYTE           UA_TYPE = 1
	UA_TYPES_BYTE            UA_TYPE = 2
	UA_TYPES_INT16           UA_TYPE = 3
	UA_TYPES_UINT16          UA_TYPE = 4
	UA_TYPES_INT32           UA_TYPE = 5
	UA_TYPES_UINT32          UA_TYPE = 6
	UA_TYPES_INT64           UA_TYPE = 7
	UA_TYPES_UINT64          UA_TYPE = 8
	UA_TYPES_FLOAT           UA_TYPE = 9
	UA_TYPES_DOUBLE          UA_TYPE = 10
	UA_TYPES_STRING          UA_TYPE = 11
	UA_TYPES_DATETIME        UA_TYPE = 12
	UA_TYPES_GUID            UA_TYPE = 13
	UA_TYPES_BYTESTRING      UA_TYPE = 14
	UA_TYPES_XMLELEMENT      UA_TYPE = 15
	UA_TYPES_NODEID          UA_TYPE = 16
	UA_TYPES_EXPANDEDNODEID  UA_TYPE = 17
	UA_TYPES_STATUSCODE      UA_TYPE = 18
	UA_TYPES_QUALIFIEDNAME   UA_TYPE = 19
	UA_TYPES_LOCALIZEDTEXT   UA_TYPE = 20
	UA_TYPES_EXTENSIONOBJECT UA_TYPE = 21
	UA_TYPES_DATAVALUE       UA_TYPE = 22
	UA_TYPES_VARIANT         UA_TYPE = 23
	UA_TYPES_DIAGNOSTICINFO  UA_TYPE = 24
)
