# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT

on:
  push:
name: Core
jobs:
  build-scan-and-publish:
    env:
      REGISTRY: ghcr.io
      REPO: ${{github.repository}}

    runs-on: ubuntu-latest
    name: Build, Scan, Publish
    steps:
      - name: Get vars
        id: vars
        run: echo ::set-output name=TAG::${GITHUB_REF##*/}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t ${{env.REGISTRY}}/${{env.REPO}}:${{steps.vars.outputs.TAG}} .

      - name: Run container scan
        uses: azure/container-scan@v0
        with:
          image-name: ${{env.REGISTRY}}/${{env.REPO}}:${{steps.vars.outputs.TAG}}
          severity-threshold: LOW

      - name: authenticate
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin $REGISTRY

      - name: publish
        run: docker push ${{env.REGISTRY}}/${{env.REPO}}:${{steps.vars.outputs.TAG}}

  licencing:
    runs-on: ubuntu-latest
    name: Licensing (SPDX)
    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1
